default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000

development:
  <<: *default
  database: fleet_management_dev
  username: kyle
  password: kyle9876
  host: localhost

test:
  <<: *default
  database: fleet_management_test
  username: kyle
  password: kyle9876
  host: localhost

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
