default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  timeout: 5000
  port: 5432
  sslmode: require

development:
  <<: *default
  database: fleet_management_dev
  username: kyle
  password: kyle9876
  host: localhost

test:
  <<: *default
  database: fleet_management_test
  username: kyle
  password: kyle9876
  host: localhost

production:
  <<: *default
  database: activeplus_production_db
  username: activeplus_production_db_user
  password: 5LnT7tTT5xP0JiCOJFfREdmfSGw76kVc
  host: dpg-d52u193e5dus73ag4oo0-a.virginia-postgres.render.com
